apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: agentic-ai

build:
  # Cleanup old images after each build to prevent layer accumulation
  local:
    useBuildkit: true
    prune: true              # Prune intermediate layers after build
    concurrency: 1           # Sequential builds to reduce disk thrashing
    push: false              # Never push to registry (local Kind cluster)
    tryImportMissing: true   # Skip build if image with same tag exists
  tagPolicy:
    inputDigest: {}          # Hash of source files - enables build avoidance
  artifacts:
    - image: agentic-ai-core
      context: .
      docker:
        dockerfile: packages/core/Dockerfile.dev
        noCache: false  # Use cache for faster builds
      sync:
        manual:
          - src: "packages/core/src/**/*.py"
            dest: /app/src
          - src: "packages/core/**/*.yaml"
            dest: /app
          - src: "blueprints/**/*.yaml"
            dest: /app/blueprints

manifests:
  rawYaml:
    - k8s/dev/deployment.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: agentic-ai-core
    namespace: agentic-ai
    port: 8001
    localPort: 8001

---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: agentic-ai-full
requires:
  - configs: ["agentic-ai"]

build:
  local:
    useBuildkit: true
    prune: true
    concurrency: 1
    push: false
    tryImportMissing: true
  tagPolicy:
    inputDigest: {}
  artifacts:
    - image: agentic-ai-ui
      context: .
      docker:
        dockerfile: packages/ui/Dockerfile.dev
      sync:
        manual:
          - src: "packages/ui/app/**/*"
            dest: /app/app
          - src: "packages/ui/components/**/*"
            dest: /app/components
          - src: "packages/ui/*.ts"
            dest: /app
          - src: "packages/ui/*.tsx"
            dest: /app
          - src: "packages/ui/*.js"
            dest: /app

manifests:
  rawYaml:
    - k8s/dev/ui-deployment.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: agentic-ai-ui
    namespace: agentic-ai
    port: 3000
    localPort: 3000
